spring.application.name=pharmacy-management-system
# This creates a file named 'pharmacy_db' in your project folder
spring.datasource.url=jdbc:h2:file:./data/pharmacy_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# This ensures the database structure is created automatically
spring.jpa.hibernate.ddl-auto=update
# Set a custom login for the Pharmacist
spring.security.user.name=admin
spring.security.user.password=pharmacy123
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# Allow H2 to be viewed in frames
spring.h2.console.settings.web-allow-others=true